cmake_minimum_required(VERSION 3.25)
project(AVManager LANGUAGES CXX)
add_executable(AVManager main.cpp AVRHandler.cpp keyboard.cpp)
target_compile_features(AVManager PRIVATE cxx_std_20)
target_link_libraries(AVManager ws2_32)
target_compile_definitions(AVManager PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX UNICODE _UNICODE)
if(MSVC)
    target_compile_options(AVManager PRIVATE /W4)
endif()
